name: Team Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update HTML
        run: |
          sed -i '/<\/body>/i <p>Updated by ${{ github.actor }} on '"$(date)"'</p>' index.html
      - name: Update README.md
        run: |
          echo "### Updated by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S')" >> README.md
